### ISSUE TITLE
about Core Gen7 Mobile microcode

### ISSUE THREAD

**Issue by maxdarksol** [intel/Intel-Linux-Processor-Microcode-Data-Files#12]
KBL-U/Y      H0       6-8e-9/c0
when I inserting the CPU patch within MMtool,I'm notice something different from before:
the version 8e 20180807 only 96KB,but version 4b 20190514 and 9a 20190312 are exceed 190KB;
4b and 9a platform type is 10 Instead of correct C0,and 9a update revision is 9E.

Why is that?
![捕获](https://user-images.githubusercontent.com/44485578/64904293-7b481380-d6fa-11e9-9b8d-4db6d1675b00.PNG)

**Comment by maxdarksol** [comment]
platform type 10 is Core Gen8 Amber Lake Y，this microcode couldn't boot up Core Gen7 Kaby Lake Y

**Comment by esyr-rh** [comment]
It seems that your tool can't parse microcode files properly. Since revision 20190312, 06-8e-09 ucode file bundles microcode for both pf_mask 0x10 and 0xc0; the same is done for quite some time in other ucode files, like 06-26-01 or 06-1c-0a or many earlier ones.

`% iucode_tool -L microcode-20180807/intel-ucode/06-8e-09`
`microcode bundle 1: microcode-20180807/intel-ucode/06-8e-09`
`  001/001: sig 0x000806e9, pf_mask 0xc0, 2018-03-24, rev 0x008e, size 98304`
`% iucode_tool -L microcode-20190312/intel-ucode/06-8e-09`
`microcode bundle 1: microcode-20190312/intel-ucode/06-8e-09`
`  001/001: sig 0x000806e9, pf_mask 0x10, 2018-10-18, rev 0x009e, size 98304`
`  001/002: sig 0x000806e9, pf_mask 0xc0, 2018-07-16, rev 0x009a, size 98304`
`% iucode_tool -L microcode-20190618/intel-ucode/06-8e-09`
`microcode bundle 1: microcode-20190618/intel-ucode/06-8e-09`
`  001/001: sig 0x000806e9, pf_mask 0x10, 2019-04-01, rev 0x00b4, size 98304`
`  001/002: sig 0x000806e9, pf_mask 0xc0, 2019-04-01, rev 0x00b4, size 99328`
`% ../iucode-tool/iucode_tool -L microcode-20190618/intel-ucode/06-26-01`
`microcode bundle 1: microcode-20190618/intel-ucode/06-26-01`
`  001/001: sig 0x00020661, pf_mask 0x01, 2009-10-23, rev 0x0104, size 5120`
`  001/002: sig 0x00020661, pf_mask 0x02, 2011-07-18, rev 0x0105, size 5120`
`% ../iucode-tool/iucode_tool -L microcode-20190618/intel-ucode/06-1c-0a`
`microcode bundle 1: microcode-20190618/intel-ucode/06-1c-0a`
`  001/001: sig 0x000106ca, pf_mask 0x01, 2009-08-25, rev 0x0107, size 5120`
`  001/002: sig 0x000106ca, pf_mask 0x04, 2009-08-25, rev 0x0107, size 5120`
`  001/003: sig 0x000106ca, pf_mask 0x08, 2009-08-25, rev 0x0107, size 5120`
`  001/004: sig 0x000106ca, pf_mask 0x10, 2009-08-25, rev 0x0107, size 5120`

**Comment by maxdarksol** [comment]
> It seems that your tool can't parse microcode files properly. Since revision 20190312, 06-8e-09 ucode file bundles microcode for both pf_mask 0x10 and 0xc0; the same is done for quite some time in other ucode files, like 06-26-01 or 06-1c-0a or many earlier ones.
> 

Is there any Windows application could extract 0xc0 microcode from  06-8e-09 ucode file bundles?
And it seems the microcode was updated C6,why only B4 there?
<img width="332" alt="捕获" src="https://user-images.githubusercontent.com/44485578/65013342-61523f00-d94d-11e9-8919-9256db9a3c09.PNG">

**Comment by maxdarksol** [comment]
I find some microcode from here[https://github.com/platomav/CPUMicrocodes/tree/master/Intel](url),Is this be the same as official code?

**Comment by esyr-rh** [comment]
While it's unofficial, it tends to be the same; note, however, that it sources microcode files not only from official Intel microcode releases for Linux (here), but also from Microsoft and Apple updates (that tend to push them before the official releases without any meaningful notices and descriptions).
